apiVersion: v1
kind: Service
metadata:
  name: gunicorn
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 30002
      nodePort: 30002
  selector:
    app: gunicorn
    miljo: test