apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gunicorn-deployment
  labels: 
    app: gunicorn
    miljo: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gunicorn
      miljo: test
  template:
    metadata:
      labels:
        app: gunicorn
        miljo: test
    spec:
      containers: 
      - name: gunicorn
        image: localhost:32000/gunicorn
        ports:
        - containerPort: 30000
      